---
title: "NFL Project"
author: "Nicolas Stevens"
date: "2023-11-29"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, include=FALSE}
library(caret)
library(ggrepel)
library(nflfastR)
library(nflplotR)
library(nflreadr)
library(dplyr)
library(regclass)
library(flextable)
library(ggplot2)
library(pROC)
library(glmnet)
library(ggpubr)

```


```{r Cleaning Data, eval=FALSE, include=FALSE}
NFL.2012.2022 <- load_pbp(2012:2022)

D_TEN <- subset(NFL.2012.2022, NFL.2012.2022$home_team == "TEN" | NFL.2012.2022$away_team == "TEN")

D_Outcome <- D_TEN[,c("game_id","week","game_date", "home_team","away_team","home_score","away_score")]

D_Fin_Outcom <- distinct(D_Outcome)

D_Fin_Outcom$TEN_win <- NA
for (i in 1:nrow(D_Fin_Outcom)) {
  if(D_Fin_Outcom$home_team[i]=="TEN" & D_Fin_Outcom$home_score[i]>=D_Fin_Outcom$away_score[i]){
    D_Fin_Outcom$TEN_win[i] <- "yes"
  } 
  
  if(D_Fin_Outcom$home_team[i]=="TEN" & D_Fin_Outcom$home_score[i]<D_Fin_Outcom$away_score[i]){
    D_Fin_Outcom$TEN_win[i] <- "no"
  } 
  
  if(D_Fin_Outcom$home_team[i]!="TEN" & D_Fin_Outcom$home_score[i]<D_Fin_Outcom$away_score[i]){
    D_Fin_Outcom$TEN_win[i] <- "yes"
  } 
  
  if(D_Fin_Outcom$home_team[i]!="TEN" & D_Fin_Outcom$home_score[i]>D_Fin_Outcom$away_score[i]){
    D_Fin_Outcom$TEN_win[i] <- "no"
  } 
}


```

```{r TEN Interceptions Thrown, eval=FALSE, include=FALSE}
TEN_OFFENSE <- subset(D_TEN, posteam == "TEN")
TEN_DEFENSE <-subset(D_TEN, posteam != "TEN")

D_TEN_O_INTS <- TEN_OFFENSE[,c("game_id","interception")]
D_TEN_O_INTS <- na.omit(D_TEN_O_INTS)
D_TEN_O_INTS <- group_by(D_TEN_O_INTS, game_id)
D_TEN_O_INTS <- mutate(D_TEN_O_INTS, TEN_SUM_O_INT = sum(interception))
D_TEN_O_INTS <- distinct(D_TEN_O_INTS, game_id, TEN_SUM_O_INT)
```

```{r TEN Defensive Interceptions, eval=FALSE, include=FALSE}
TEN_DEFENSE <-subset(D_TEN, posteam != "TEN")

D_TEN_D_INTS <- TEN_DEFENSE[,c("game_id","interception")]
D_TEN_D_INTS <- na.omit(D_TEN_D_INTS)
D_TEN_D_INTS <- group_by(D_TEN_D_INTS, game_id)
D_TEN_D_INTS <- mutate(D_TEN_D_INTS, TEN_SUM_D_INT = sum(interception))
D_TEN_D_INTS <- distinct(D_TEN_D_INTS, game_id, TEN_SUM_D_INT)


```

```{r TEN Offensive fumbles lost (Turnovers), eval=FALSE, include=FALSE}
D_TEN_O_FUM <- TEN_OFFENSE[,c("game_id","fumble_lost")]
D_TEN_O_FUM <- na.omit(D_TEN_O_FUM)
D_TEN_O_FUM <- group_by(D_TEN_O_FUM, game_id)
D_TEN_O_FUM <- mutate(D_TEN_O_FUM, TEN_SUM_O_FUM = sum(fumble_lost))
D_TEN_O_FUM <- distinct(D_TEN_O_FUM, game_id, TEN_SUM_O_FUM)



```

```{r TEN Defensive Fumbles forced and Recovered, eval=FALSE, include=FALSE}
D_TEN_D_FUM <- TEN_DEFENSE[,c("game_id","fumble_lost")]
D_TEN_D_FUM <- na.omit(D_TEN_D_FUM)
D_TEN_D_FUM <- group_by(D_TEN_D_FUM, game_id)
D_TEN_D_FUM <- mutate(D_TEN_D_FUM, TEN_SUM_D_FUM = sum(fumble_lost))
D_TEN_D_FUM <- distinct(D_TEN_D_FUM, game_id, TEN_SUM_D_FUM)



```

```{r TEN Turnover Margin, eval=FALSE, include=FALSE}
D_Fin_Outcom$TurnoverMargin <- D_TEN_D_FUM$TEN_SUM_D_FUM + D_TEN_D_INTS$TEN_SUM_D_INT - D_TEN_O_FUM$TEN_SUM_O_FUM - D_TEN_O_INTS$TEN_SUM_O_INT


```


```{r Turnover Margin Box Plot, eval=FALSE, include=FALSE}

D_Fin_Outcom$Year <- substr(D_Fin_Outcom$game_id,1,4)





```

```{r TEN Third Down Converted, eval=FALSE, include=FALSE}
D_TEN_O_3DC <- TEN_OFFENSE[,c("game_id","third_down_converted")]
D_TEN_O_3DC <- na.omit(D_TEN_O_3DC)
D_TEN_O_3DC <- group_by(D_TEN_O_3DC, game_id)
D_TEN_O_3DC <- mutate(D_TEN_O_3DC, TEN_SUM_O_3DC = sum(third_down_converted))
D_TEN_O_3DC <- distinct(D_TEN_O_3DC, game_id, TEN_SUM_O_3DC)

D_Fin_Outcom$ThirdDownConverted <- D_TEN_O_3DC$TEN_SUM_O_3DC

```

```{r Opponent Third Down Converted, eval=FALSE, include=FALSE}
D_3DC_ALWD <- TEN_DEFENSE[,c("game_id","third_down_converted")]
D_3DC_ALWD <- na.omit(D_3DC_ALWD)
D_3DC_ALWD <- group_by(D_3DC_ALWD, game_id)
D_3DC_ALWD <- mutate(D_3DC_ALWD, D_SUM_ALWD_3DC = sum(third_down_converted))
D_3DC_ALWD <- distinct(D_3DC_ALWD, game_id, D_SUM_ALWD_3DC)

D_Fin_Outcom$ThirdDownAllowed <- D_3DC_ALWD$D_SUM_ALWD_3DC

```

```{r Number of Times TEN sacked, eval=FALSE, include=FALSE}
D_TEN_SACKED <- TEN_OFFENSE[,c("game_id","sack")]
D_TEN_SACKED<- na.omit(D_TEN_SACKED)
D_TEN_SACKED<- group_by(D_TEN_SACKED, game_id)
D_TEN_SACKED<- mutate(D_TEN_SACKED, D_SUM_TEN_SACKED = sum(sack))
D_TEN_SACKED<- distinct(D_TEN_SACKED, game_id, D_SUM_TEN_SACKED)

D_Fin_Outcom$TennSacked <- D_TEN_SACKED$D_SUM_TEN_SACKED

```

```{r Number of sacks for TEN, eval=FALSE, include=FALSE}
D_TEN_D_SACK <- TEN_DEFENSE[,c("game_id","sack")]
D_TEN_D_SACK<- na.omit(D_TEN_D_SACK)
D_TEN_D_SACK<- group_by(D_TEN_D_SACK, game_id)
D_TEN_D_SACK<- mutate(D_TEN_D_SACK, D_SUM_TEN_D_SACK = sum(sack))
D_TEN_D_SACK<- distinct(D_TEN_D_SACK, game_id, D_SUM_TEN_D_SACK)

D_Fin_Outcom$TennSackGotten <- D_TEN_D_SACK$D_SUM_TEN_D_SACK
```

```{r TEN Rushing Yards, eval=FALSE, include=FALSE}

D_TEN_Rush_Yds <- TEN_OFFENSE[,c("game_id","rushing_yards")]
D_TEN_Rush_Yds<- na.omit(D_TEN_Rush_Yds)
D_TEN_Rush_Yds<- group_by(D_TEN_Rush_Yds, game_id)
D_TEN_Rush_Yds<- mutate(D_TEN_Rush_Yds, D_SUM_TEN_Rush_Yds = sum(rushing_yards))
D_TEN_Rush_Yds<- distinct(D_TEN_Rush_Yds, game_id, D_SUM_TEN_Rush_Yds)

D_Fin_Outcom$RushingYards <- D_TEN_Rush_Yds$D_SUM_TEN_Rush_Yds
```


```{r TEN Pass Attempts, eval=FALSE, include=FALSE}
D_TEN_Pass_Att <- TEN_OFFENSE[,c("game_id","pass_attempt")]
D_TEN_Pass_Att<- na.omit(D_TEN_Pass_Att)
D_TEN_Pass_Att<- group_by(D_TEN_Pass_Att, game_id)
D_TEN_Pass_Att<- mutate(D_TEN_Pass_Att, D_SUM_TEN_Pass_Att = sum(pass_attempt))
D_TEN_Pass_Att<- distinct(D_TEN_Pass_Att, game_id, D_SUM_TEN_Pass_Att)

D_Fin_Outcom$PassAttempts <- D_TEN_Pass_Att$D_SUM_TEN_Pass_Att
```


```{r Defensive Incompletions Forced, eval=FALSE, include=FALSE}
D_TEN_D_INC <- TEN_DEFENSE[,c("game_id","incomplete_pass")]
D_TEN_D_INC<- na.omit(D_TEN_D_INC)
D_TEN_D_INC<- group_by(D_TEN_D_INC, game_id)
D_TEN_D_INC<- mutate(D_TEN_D_INC, D_SUM_TEN_D_INC = sum(incomplete_pass))
D_TEN_D_INC<- distinct(D_TEN_D_INC, game_id, D_SUM_TEN_D_INC)

D_Fin_Outcom$OpponentIncompletions <- D_TEN_D_INC$D_SUM_TEN_D_INC
```

```{r Point Differential, eval=FALSE, include=FALSE}
D_Fin_Outcom$TEN_PointDifferential <- NA
for (i in 1:nrow(D_Fin_Outcom)) {
  if(D_Fin_Outcom$home_team[i]=="TEN"){
    D_Fin_Outcom$TEN_PointDifferential[i] <- D_Fin_Outcom$home_score[i] - D_Fin_Outcom$away_score[i]
  } 
  if(D_Fin_Outcom$home_team[i]!="TEN"){
    D_Fin_Outcom$TEN_PointDifferential[i] <- D_Fin_Outcom$away_score[i] - D_Fin_Outcom$home_score[i]
  } 
}
```

```{r Yearly Results, eval=FALSE, include=FALSE}
YearlyResults <- c()
YearlyResults <- data.frame(Year = c("2012","2013","2014","2015","2016","2017","2018","2019","2020","2021", "2022"))
YearlyResults$WinTotal <- NA
for(i in 2012:2022){
  Formatted <- as.character(i)
Wins <- sum(D_Fin_Outcom$TEN_win[which(D_Fin_Outcom$Year == Formatted)] == "yes")
YearlyResults$WinTotal[i-2011] <- Wins
}

YearlyResults$PointDifferential <- NA
for(i in 2012:2022){
  Formatted <- as.character(i)
PointDiff <- sum(D_Fin_Outcom$TEN_PointDifferential[which(D_Fin_Outcom$Year == Formatted)])
YearlyResults$PointDifferential[i-2011] <- PointDiff
}

YearlyResults$WinningSeason <- NA
for(i in 2012:2022){
  Formatted <- as.character(i)
  if(YearlyResults$WinTotal[i-2011] >= 9){
    YearlyResults$WinningSeason[i-2011] <- "Yes"
  }
  else {
    YearlyResults$WinningSeason[i-2011] <- "No"
  }

}

YearlyResults
```

```{r Saving Data, eval=FALSE, include=FALSE}
save(D_Fin_Outcom, YearlyResults, YRFlexFin, YearlyWins, YearlyPointDiff, file = "CompiledTENNFLData.RData")

```


```{r Graphical Display 1, eval=FALSE, include=FALSE}
load("CompiledTENNFLData.RData")

YRFlex <- flextable(YearlyResults)
YRFlexFin <- style(YRFlex, pr_t = fp_text(color = "red"), pr_c = fp_cell(border = fp_border(color = "lightblue")), part = "all") %>%
  bg(bg = "navy", part = "all") 

YRFlexFin

 YearlyWins <- ggplot(data = YearlyResults, mapping = aes(x = Year, y = WinTotal) ) +
  geom_bar(stat = "Identity", color = "red", fill = "navy") +
  theme_minimal() +
   geom_hline(yintercept = 0) + 
   labs(title = "Wins by Season") +
   xlab("Season") +
  ylab("Win Total")

 
 YearlyWins
 
  YearlyPointDiff <- ggplot(data = YearlyResults, mapping = aes(x = Year, y = PointDifferential) ) +
  geom_bar(stat = "Identity", color = "red", fill = "navy") +
   geom_hline(yintercept = 0) +
    labs(title = "Yearly Point Differential") +
   xlab("Season") +
  ylab("Point Differential") +
    theme_minimal()

YearlyPointDiff

```

```{r Graphical Displays 2, echo=FALSE}
load("CompiledTENNFLData.RData")

YRFlexFin
YearlyWins
YearlyPointDiff


```

```{r Holdout Set Creation, include=FALSE}
D_Train <- subset(D_Fin_Outcom, Year != "2022")
D_Test <- subset(D_Fin_Outcom, Year=="2022")


```

```{r GLMNet Model, include=FALSE}

fitControl <- trainControl(method="cv", number=5)
glmnetGrid <- expand.grid(alpha = seq(0, 1, .1),
                          lambda = 10^seq(-3,-0.5,by=.5)) 
colnames(D_Train)
GLMnet <- caret::train(TEN_PointDifferential ~ TurnoverMargin + ThirdDownConverted + ThirdDownAllowed + TennSacked + TennSackGotten + RushingYards + PassAttempts + OpponentIncompletions,
                data=D_Train, 
                method='glmnet',  # 1 pt
                tuneGrid=glmnetGrid,
                trControl=fitControl, 
                preProc = c("center", "scale"))
GLMnet$bestTune
GLMnet$results[rownames(GLMnet$bestTune),]



```

```{r GBM, include=FALSE}
gbmGrid <- expand.grid(n.trees=c(2000),
                       shrinkage=c(.002),
                       interaction.depth=c(1,2),
                       n.minobsinnode=c(10))
gbmGrid

GBM <- caret::train( TEN_PointDifferential ~ TurnoverMargin + ThirdDownConverted + ThirdDownAllowed + TennSacked + TennSackGotten + RushingYards + PassAttempts + OpponentIncompletions,
              data=D_Train,
             method="gbm",
             tuneGrid=gbmGrid,
             trControl=fitControl,
             preProc=c("center","scale"),
             verbose=FALSE)

# Best GBM:
GBM$results[nrow(GBM$bestTune), ]


```


```{r Random Forest, include=FALSE}
fitControl <- trainControl(method="cv",number=5)

rfGrid <- expand.grid(mtry=c(2, 5))
rfGrid

FOREST <- caret::train(TEN_PointDifferential ~ TurnoverMargin + ThirdDownConverted + ThirdDownAllowed + TennSacked + TennSackGotten + RushingYards + PassAttempts + OpponentIncompletions,
                data=D_Train, 
                method="rf",
                tuneGrid=rfGrid,
                trControl=fitControl,
                preProcess=c("center","scale"))


FOREST$results[nrow(FOREST$bestTune), ]


```


```{r Prediction, eval=FALSE, include=FALSE}
GLMnet$results[rownames(GLMnet$bestTune),]
FOREST$results[nrow(FOREST$bestTune), ]
GBM$results[nrow(GBM$bestTune), ]
#GLMnet vs Random Forest
(10.04826- 8.53309)/ 1.767612
#GLMnet vs GBM
(10.07559 -  8.53309) / 1.767612

ModelData <- data.frame(Model = c("GLMnet","Random Forest", "GBM"), RMSE = c(8.53309,10.04826, 10.07559), RMSESD = c(1.767612,0.2432264,0.6188943))

ModelFlex <- flextable(ModelData)
ModelFlexFin <- style(ModelFlex, pr_t = fp_text(color = "red"), pr_c = fp_cell(border = fp_border(color = "light blue")), part = "all") %>%
  bg(bg = "navy", part = "all") 

ModelFlexFin

D_Test$predict_TEN_ScoreDiff <- predict(GLMnet, D_Test)

D_Test$Predicted_Scorediff_RN <- c(3.7571708,-11.2871466,3.3924312,5.7320289,-0.7291635,6.0255880,14.8512654,9.9101885, 9.6192555, -5.6489020, -0.7956502,-9.5508832,-19.9315508,-0.9331460,-9.7958390,-2.475163, -5.9477661)



Comparisonplot <- plot(D_Test$TEN_PointDifferential, D_Test$predict_TEN_ScoreDiff,
     xlim=c(-20,20), ylim=c(-20,20), pch=15);abline(a=0,b=1)

SuperiorCompPlot <- ggscatter(data = D_Test, 'TEN_PointDifferential', 'Predicted_Scorediff_RN', color = "red", xlim = c(-30,30), ylim = c(-30,30), xlab = "Actual Point Differential", ylab = "Predicted Point Differential") + geom_abline(slope = 1, intercept = 0) + bgcolor("#4790DE") + border(color = "navy") + ggtitle("Point Differential - Predicted vs Actual")
#RMSE on Naive
sqrt(mean((D_Test$TEN_PointDifferential - mean(D_Train$TEN_PointDifferential) )^2 ))

#RMSE on GLMnet
sqrt(mean((D_Test$TEN_PointDifferential - D_Test$predict_TEN_ScoreDiff)^2 ))

save(ModelFlexFin,Comparisonplot,SuperiorCompPlot, file = "NFLGraphsAndTables2.RData")
```

```{r Graphical Displays 3}
load("NFLGraphsAndTables2.RData")
ModelFlexFin
SuperiorCompPlot

coef.glmnet(GLMnet$finalModel, s = 0.3162278)
FinalModelCoef <- data.frame(CoeffcientName = c("Intercept","Turnover Margin","Third Down Converted","Third Down Allowed","Tennessee Sack Allowed","Tennessee Sack","Rushing Yards","Passing Attempts","Opponent Incompletions"), Estimates = c(-1.8452381,6.0208795,2.7844730,-1.1556714, -2.3936104,2.7132251, 3.4065384, -0.5455789, 3.3440880))


FMC <- flextable(FinalModelCoef)
FMCFin <- style(FMC, pr_t = fp_text(color = "red"), pr_c = fp_cell(border = fp_border(color = "lightblue")), part = "all") %>%
  bg(bg = "navy", part = "all")


```

